### ISSUE TITLE
Music / SFX

### ISSUE THREAD

**Issue by timbledum** [dannyso16/pynasour#3]
If you like I can have a go at adding some music and sound effects to this game? Happy if you already have plans though. :)

**Comment by dannyso16** [comment]
I'm planning do so, but I don't have skill to make sounds.  I impremented function which combines two pyxel files (image file and sound file. see `util.py`.) I'm glad you help me.

**Comment by timbledum** [comment]
No problem – merge request now in! I ended up editing the main asset file directly rather than using/ the util functionality – hope that works.
